### ISSUE TITLE
Create a Footer component

### ISSUE THREAD

**Issue by Sedoid** [ngigordon/Housing-kamer#3]
Create a footer component identical to the design

**Comment by BerinyuyAnabi** [comment]
On this

**Comment by Sedoid** [comment]
Noted

**Comment by BerinyuyAnabi** [comment]
Done.

**Comment by Sedoid** [comment]
gimme a moment to verify

**Comment by Sedoid** [comment]
Logan, could you leave your mail here

**Comment by BerinyuyAnabi** [comment]
***@***.***

**Comment by Sedoid** [comment]
i'm not sure if this is what you wrote... but this is what i see 
Your mail:  ***@***.***

**Comment by Sedoid** [comment]
i'm not sure if this is what you wrote... but this is what I see
Your mail:   ***@***.***

**Comment by Sedoid** [comment]
i'm not sure if this is what you wrote... but this is what i see
Your mail: ***@***.***
